### ISSUE TITLE
Failed to deploy with Netlify as submodule

### ISSUE THREAD

**Issue by chug6** [nodejh/hugo-theme-cactus-plus#54]
First of all, thanks a lot for this very nice theme.

I try to install the theme as a submodule, in order to use deployment with netlify. But it failed at deployment. 

I let you some output from netlify log

7:44:29 PM: Error: Unable to find theme Directory: /opt/build/repo/site/themes/hugo-theme-cactus-plus
7:44:29 PM: [18:44:29] 'build' errored after 35 ms
7:44:29 PM: [18:44:29] Error: Hugo build failed
7:44:29 PM:     at formatError (/opt/build/repo/node_modules/gulp/bin/gulp.js:169:10)
7:44:29 PM:     at Gulp.<anonymous> (/opt/build/repo/node_modules/gulp/bin/gulp.js:195:15)
7:44:29 PM:     at emitOne (events.js:96:13)
7:44:29 PM:     at Gulp.emit (events.js:188:7)
7:44:29 PM:     at Gulp.Orchestrator._emitTaskDone (/opt/build/repo/node_modules/orchestrator/index.js:264:8)
7:44:29 PM:     at /opt/build/repo/node_modules/orchestrator/index.js:275:23
7:44:29 PM:     at finish (/opt/build/repo/node_modules/orchestrator/lib/runTask.js:21:8)
7:44:29 PM:     at cb (/opt/build/repo/node_modules/orchestrator/lib/runTask.js:29:3)
7:44:29 PM:     at ChildProcess.<anonymous> (/opt/build/repo/gulpfile.babel.js:85:7)
7:44:29 PM:     at emitTwo (events.js:106:13)
7:44:30 PM: npm
7:44:30 PM:  ERR! Linux 4.4.86+
7:44:30 PM: npm ERR! argv "/opt/buildhome/.nvm/versions/node/v6.11.1/bin/node" "/opt/buildhome/.nvm/versions/node/v6.11.1/bin/npm" "run" "build"
7:44:30 PM: npm ERR! node v6.11.1
7:44:30 PM: npm ERR! npm  v3.10.10
7:44:30 PM: npm ERR! code ELIFECYCLE
7:44:30 PM: npm ERR! victor-hugo@1.0.0 build: `gulp build`
7:44:30 PM: npm ERR! Exit status 1
7:44:30 PM: npm ERR!
7:44:30 PM: npm ERR! Failed at the victor-hugo@1.0.0 build script 'gulp build'.
7:44:30 PM: npm ERR! Make sure you have the latest version of node.js and npm installed.
7:44:30 PM: npm ERR! If you do, this is most likely a problem with the victor-hugo package,
7:44:30 PM: npm ERR! not with npm itself.
7:44:30 PM: npm ERR! Tell the author that this fails on your system:
7:44:30 PM: npm ERR!     gulp build
7:44:30 PM: npm ERR! You can get information on how to open an issue for this project with:
7:44:30 PM: npm ERR!     npm bugs victor-hugo
7:44:30 PM: npm ERR! Or if that isn't available, you can get their info via:
7:44:30 PM: npm ERR!     npm owner ls victor-hugo
7:44:30 PM: npm ERR! There is likely additional logging output above.
7:44:30 PM: npm ERR! Please include the following file with any support request:
7:44:30 PM: npm ERR!     /opt/build/repo/npm-debug.log
7:44:30 PM: Caching artifacts

As a workaround I download the theme manually, and it work this way to deployed

All the best,
Hugues

**Comment by josephearl** [comment]
I believe Netlify supports Git submodules now - I have my site setup using this as submodule and it deploys fine
